---
title:  "Farmer's Markets"
author: "Beth Wolfset"
date:   "October 26, 2016"
output:  html_document:
  keep_md: true
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Find Farmers Markets

This application will allow users to find Farmer's Markets in the United States.  A map of the United States is displayed with all Farmers Markets marked.

Since there are thousands of markets across the US, the application allows the user to click on a state from a drop down list.  The application will zoom in to that state, coloring the markers to make them more visible.

In some areas, the concentration of markets is still dense.  The user can choose a city from a drop down list.

To user can click on the market circle to get details including its name, location, season of operation, and hours.

A Farmers Market is a place where local farmers assemble to sell their goods directly to the public.  These are usually run on a regular basis in that location throughout the season. Most consist of tables or booths and are 'open-air'. They could carry vegetables, fruits, bread and other bakery items, meats, eggs and prepared foods. 

The data has been optained from [the United States Government Data  Catalog](https://catalog.data.gov/dataset/farmers-markets-geographic-data).
The [Farmers Market Export](https://apps.ams.usda.gov/FarmersMarketsExport/ExcelExport.aspx) was downloaded and is in the data directory of the shiny project.

The shiny application is available at [Shinyapps.io](https://bswolfset.shinyapps.io/Market/).

Source code is available on [GitHub](https://github.com/BSWolfset/Market/tree/gh-pages).



