---
title       : Farmers Market Finder
subtitle    : Developing Data Product - Course Assignment
author      : Beth Wolfset
job         : Data Architect
framework   : io2012  # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, quiz, bootstrap]      # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

---

## The Farmers Market Find Application
* Application allows users to find Farmer's Markets in the United States
* Users can focus the map by
    + Pick a state from a drop down list
    + Pick a city from a drop down list
* Users can click the market circle to get details including its name, location, season of operation, and hours.

* Farmers Market - place where local farmers assemble to sell their goods directly to the public

---

## Data Handling
* Data from United States Government Data Catalog https://catalog.data.gov/dataset/farmers-markets-geographic-data
* Downloded the dataset https://apps.ams.usda.gov/FarmersMarketsExport/ExcelExport.aspx
* Removed rows with missing lattitude of longitude
* Trimmed white space
* City data in inconsistent - changed to uppercase
* Data set contains market demographics: MarketName, Address, Coordinates, Website, Other Media Handles
* Data set contains season and hours
* Data set contains products: Bakedgoods, Vegetables/Fruit, Cheese/Eggs,  Crafts, Flowers/Plants/Trees, Meat/Seafood, Other

---

## Farmers Market Distribution by State

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(ggplot2)
library(sqldf)
FarmMarketRaw <-
  read.csv("~/R/win-library/3.3/Market/data/FMExport.csv", na.strings = c("NA", "", "#DIV/0!"), header = TRUE, strip.white = TRUE)
StRegDF <- cbind(as.data.frame(state.name), reg=state.region)
names(StRegDF)[names(StRegDF)=="state.name"] <- "State"
StRegDF <- sqldf("select reg, FarmMarketRaw.State, count(*) as cnt
                    from FarmMarketRaw
                    Join StRegDF on FarmMarketRaw.State = StRegDF.State
                   Where x is not null
                     and y is not null
                     and FarmMarketRaw.State is not null
                   group by reg, FarmMarketRaw.State")
StRegDF$State <- factor(StRegDF$State)

RegDF <- sqldf("select reg, count(*) as cnt
                  from StRegDF
                group by reg ")

qplot(data=StRegDF, cnt, State, label=State,
  main='Farmers Market Distribution', ylab='State', xlab='Number of Markets') +
  geom_text(aes(colour=StRegDF$reg), hjust=0, nudge_x=.05) + theme(axis.text.x = element_blank())


```

---

## Next Steps

* Bugs
    + Browsers work inconsistently: Shiny app works in Firefox.  Does not work in IE.  Limited success in Chrome, Edge.
    + Allow the ability to go back to All States

* Enhancements
    + Allow user to specify product
    + Data for some markets suspect.  Not updated and season in in the past.  Exclude from app?

